<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-CJOBJ4OK" failures="1" tests="1" name="API Tests" time="0.015" errors="0" timestamp="16 Feb 2022 11:03:27 GMT">
  <testcase classname="ui.selenium_tests.Test2API" name="verifyHardGoodInRestResponse" time="0.003">
    <failure type="java.lang.NoClassDefFoundError" message="io/restassured/RestAssured">
      <![CDATA[java.lang.NoClassDefFoundError: io/restassured/RestAssured
at ui.selenium_tests.Test2API.verifyHardGoodInRestResponse(Test2API.java:13)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: io.restassured.RestAssured
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
... 21 more
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyHardGoodInRestResponse -->
</testsuite> <!-- API Tests -->
